app/models/tracks.py
from app import db


class Layer(db.EmbeddedDocument):
    layerName = db.StringField(required = True, max_length=100)
    layerPath = db.StringField(required = True)
    createdBy = db.StringField(required = True)
    startTime = db.DecimalField(required = True)
    layerID = db.ObjectIdField()

class Track(db.Document):
    trackName = db.StringField(required=True, max_length=100) 
    originalArtist = db.StringField(required = True, max_length = 100)
    createdBy = db.StringField(required = True)
    layers = db.ListField(db.EmbeddedDocumentField('Layer'))
    hidden = db.BooleanField(default = False)

app/routes/home.py
from flask import Blueprint, render_template
from app.models.tracks import Track,Layer
from bson.objectid import ObjectId


home = Blueprint('home', __name__)


@home.route('/')
def home_page():
    """The home page."""

    # 11/6: Commenting out for now because things are breaking
    #tracks = Track.objects()
    return render_template('index.html')#, tracks = tracks)

@home.route('/howto')
def howto_page():
	return render_template('howto.html')

app/routes/login.py
import app
from flask import Blueprint, redirect, url_for, render_template
from flask.ext.login import LoginManager, UserMixin, login_user, logout_user, current_user
from app.models.oauth import OAuthSignIn
from app import db
from app.models.user import User

login = Blueprint('login', __name__, url_prefix='/login')


@login.route('/')
def index():
    return redirect(url_for('home.home_page'))

@login.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home.home_page'))

@login.route('/authorize/<provider>')
def oauth_authorize(provider):
    if not current_user.is_anonymous:
        return redirect(url_for('login.index'))
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()


@login.route('/callback/<provider>')
def oauth_callback(provider):
    if not current_user.is_anonymous:
        return redirect(url_for('login.index'))
    oauth = OAuthSignIn.get_provider(provider)
    social_id, username, email = oauth.callback()
    if social_id is None:
        flash('Authentication failed.')
        return redirect(url_for('login.index'))
    print social_id
    print username
    print email
    try:
        user = User.objects().get(social_id=social_id)
    except User.DoesNotExist:
        user = User(social_id=social_id, username=username, email=email)
        user.save()

    login_user(user, True)
    return redirect(url_for('login.index'))


if __name__ == '__main__':
    print "Compiles successfully!"

app/routes/track.py
from flask import Blueprint, render_template,request, redirect, url_for, jsonify
from flask.ext.login import login_required, current_user
from app.models.tracks import Track,Layer
from bson.objectid import ObjectId
import os, datetime
from app import db
from mongoengine import Q


track = Blueprint('track', __name__, url_prefix='/track')

@track.route('/', methods = ["GET","POST"])
def all_tracks():
	tracks = Track.objects()
	return render_template("all.html", tracks = tracks, search = "")


#FIND BETTER WAY TO QUERY
@track.route('/search', methods = ["GET","POST"])
def search():
	if request.method == "POST":
		search = request.form["search"]
		tracks = Track.objects(Q(trackName = search) | Q(originalArtist = search) | Q(createdBy = search))
	return render_template("all.html", tracks = tracks, search = search)


@track.route('/<trackID>')  
def track_page(trackID):
    track = Track.objects().get(id = ObjectId(trackID))
    return render_template('track.html',track = track)



@track.route('/save/<trackID>', methods = ["GET","POST"])
@login_required
def save_layer(trackID):
	if request.method == "POST":
		track = Track.objects().get(id = ObjectId(trackID))

		layerName = request.form['layerName']
		startTime = request.form['startTime']
		layerFile = request.files['layerFile']

		layerId = ObjectId()
		layerPath = filePath(track,layerId,layerName,startTime)
		layerFile.save('app'+layerPath)

		newLayer = Layer(
				layerName = layerName,
				layerPath = layerPath,
				createdBy = current_user.username,
				startTime = startTime,
				layerID = layerId )

		track.layers.append(newLayer)
		track.save()
	
	return jsonify(url = url_for('track.track_page', trackID=track.id))


@track.route('/delete/<trackID>/<layerID>')
@login_required
def del_layer(trackID,layerID):
	track = Track.objects().get(id = ObjectId(trackID))	
	track.update(pull__layers__layerID=ObjectId(layerID))
	track.save()

	if len(track.layers)-1 == 0: #why is -1 necessary?
		track.delete()
		return redirect( url_for('track.all_tracks') )
	return redirect( url_for('track.track_page', trackID=trackID))


@track.route('deletetrack/<trackID>')
@login_required
def del_track(trackID):
	track = Track.objects().get(id = ObjectId(trackID))	
	if current_user.username == track.createdBy:
		track.delete()
	return redirect( url_for('track.all_tracks') )



@track.route('/new', methods = ["POST","GET"])
@login_required
def new_track():
	if request.method == "POST":
		
		trackName = request.form['trackName']
		startTime = request.form['startTime']
		isHidden = request.form['isHidden']
		layerFile = request.files['layerFile']
	

		track = Track(
			trackName = trackName,
			createdBy = current_user.username, 
			originalArtist = request.form['originalArtist'],
			hidden = bool(int(isHidden)),
			)
		track.save()


		layerName =  trackName + " Original"

		layerId = ObjectId()
		layerPath = filePath(track,layerId,layerName,startTime)
		layerFile.save('app'+layerPath)

		newLayer = Layer(
				layerName = layerName,
				layerPath = layerPath,
				createdBy = current_user.username,
				startTime = startTime,
				layerID = layerId )

		track.layers.append(newLayer)
		track.save()




		return jsonify(url = url_for('track.track_page', trackID=track.id))
	return render_template('newTrack.html')


@track.route('/cleanup')
@login_required
def cleanup():
	filePath ='app/static/music/'
	if current_user.username != "itchynose27":
		return redirect( url_for('home.home_page') )

	else:
		fileNames = os.listdir(filePath)
		fileNames = [x for x in fileNames if x.endswith(".wav")]
		
		for filename in fileNames:
			layerId = filename.split("__")[0]
 			print layerId
			existingTrack = Track.objects(layers__layerID = ObjectId(layerId)).first()

			if existingTrack == None:
				os.remove(filePath+filename)



		return str(fileNames)



def filePath(track,layerId, layerName, startTime):
	pathName = "/static/music/"+str(layerId)+"__"+str(track.id)+"__"+layerName+"__"+startTime.replace(".","-")+".wav"
	return pathName.replace(" ","")

app/routes/user.py
from flask import Blueprint, render_template,request, redirect, url_for, jsonify
from flask.ext.login import login_required, current_user
from app.models.tracks import Track,Layer
from app import db


user = Blueprint('user', __name__, url_prefix='/user')

@user.route('/<username>')
def findUser(username): #better way to query?
	tracks = Track.objects(createdBy = username)
	return render_template("all.html", tracks = tracks, search = username)

app/templates/all.html
{% extends "navbar.html" %} 
{% block content %} 

  <nav>
    <div class="nav-wrapper white">
      <form id = "SearchForm" action="{{ url_for('track.search')}}" method = "post">
        <div class="input-field">
           <input id = "search" type="search" type="text" placeholder = "Search For Tracks" name="search" required />
          <label for="search"><i class="material-icons grey-text">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form>

    </div>
  </nav>

      <div class="container">
      	<div class="row">
			   <div class="col s6">

                <h3>All Available Tracks {%if search != "" %} ({{search}}) {% endif %} </h3>
                 {%for track in tracks %}
                  {%if track.hidden == False or current_user.username == track.createdBy %}
                      <br>
                         <a href="{{ url_for('track.track_page', trackID=track.id) }}">
                        <div class = "white-text card-panel trackBox hoverable"> 
                        <h4>{{track.trackName}}</h4>
                        <ul>
                          <li> Original Artist: {{track.originalArtist}}
                          <li> Created by: {{track.createdBy}}
                          {%if track.hidden%}
                          <li> (Hidden Track)
                          {%endif%}
                        </ul> 
                      </div>
                      </a>
                  {%endif%}
 
                 {% endfor %}
      

          </div>
          <div class="col s6"></div>

		    </div>

      </div>

{% endblock %}

app/templates/allOld.html
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Web Audio API</title>


<style>
body{
	color: white;
	background-color: black;
	text-decoration: none;
}

.trackBox{
	color:white;
	background-color:#ce1886;
	display: inline-block;
	width: 300px;
	margin-top: 20px;
	margin-left: 50px;
	padding-left: 10px;
	border-radius: 10px;
	border: 1px solid white;
}

.trackBox:hover{
	background-color: #152430;
}

</style>

</head>

<body>

{% if current_user.is_authenticated %}
  Hi {{ current_user.username }}!
{% endif %}
{% if not current_user.is_authenticated %}
<a href= "{{ url_for('login.index') }}">login</a>
{% endif %}
<br><br><br>
<form id = "SearchForm" action="{{ url_for('track.search')}}" method = "post">
  Search Query:<br>
  <input type="text" placeholder = "i.e. Single Ladies" name="search" required />
  <button type="submit">Search Tracks</button>
</form> 

<br>
<a href ="{{url_for('track.all_tracks')}}"> See all tracks </a>

<h1>All Available Tracks {%if search != "" %} ({{search}}) {% endif %} </h1>
 <a href = "{{ url_for('track.new_track') }}"><div class = "trackBox">New Track</div></a> 

 {%for track in tracks %}
 	 		<br>
	 			 <a href="{{ url_for('track.track_page', trackID=track.id) }}">
				<div class = "trackBox"> 
	 			{{track.trackName}} 
	 			<ul>
	 				<li> Original Artist: {{track.originalArtist}}
	 				<li> Created by: {{track.createdBy}}
	 			</ul> 
	 		</div>
	 		</a>

 {% endfor %}
</body>
</html>

app/templates/howto.html
{% extends "navbar.html" %} 
{% block content %} 


  <div class="parallax-container" style="height:500px">
  	   <div class="parallax"><img src="/static/img/drums.jpg"></div>
  </div>

<div class="section howToSection z-depth-5">
	<div id="howItWorks">
    <p class = "center-align"> How it works </p>
  </div>
  <div class="container">   
    <h4 class="center-align howtoHeader"> Create a New Track </h4>
    <p class="center-align">
      Navigate to the New Track page. Enter the <i>Name of Track</i> (i.e. Single Ladies) and <i>Original Artist</i> (i.e. Beyoncé). These two fields will help other users looking to collaborate on specific songs find your track. Selecting <i>Hidden</i> will prevent your track from turning up when searched. However, it will still be accessible from your account and by anyone with the URL. This feature is useful for private collaborations. Finally, to create the track you can either record directly from your browser by hitting <i>Add Recording for New Track</i> or you can upload a music file to start the track by selecting <i>Upload Audio to Start Track</i>
    </p>

    <div class = "row center">
    <img class="z-depth-2 responsive-img" src="/static/img/howto1.png">
  </div>

    <p class="center-align">
      If you select <i>Add Recording for New Track</i> you will hear a 3 second countdown, after which the recording will begin. Once you are done recording, select <i>Add Recording for New Track</i> again to stop recording. The following waveform will then be displayed. Hit <i> Play </i> to play the recording and decide if you are satisfied with it. If you are not, you many <i> Delete Recording</i> and try again, or <i>Save Recording</i> as a new track.
    </p>

    <div class = "row center">
    <img class="z-depth-2 responsive-img" src="/static/img/howto2.png">
  </div>

  </div>
</div>

  <div class="parallax-container" style="height:400px">
    <div class="parallax"><img src="/static/img/piano.jpg"></div>
  </div>


<!--Adding A Harmony --> 
  <div class="section howToSection z-depth-5">
  <div class="container">   
    <h4 class="center-align howtoHeader"> Adding Harmonies </h4>
    <p class="center-align">
      Note: you must be logged in to add harmonies <br>
     Navigate to a track page. Click to seek to the location where you want to start recording from. You can also just record from the beginning of the track. Hit <i>Start/Stop Recording</i>. You will be given a 3 second countdown and then recording will begin at the location of the trackbar. <em> Headphones and a mic are strongly suggested for recording to avoid feedback. </em> To finish recording hit <i>Start/Stop Recording</i>.
    </p>

    <div class = "row center">
    <img class="z-depth-2 responsive-img" src="/static/img/howto3.png">
  </div>

    <p class="center-align">
      After you are finished recording, the waveform will then be displayed. Play the recording and decide if you are satisfied with it. If you are not, you many <i> Delete Recording</i> and try again, or <i>Save Recording</i> to the track as an additional layer.
    </p>

     <div class = "row center">
    <img class="z-depth-2 responsive-img" src="/static/img/howto4.png">
    </div>

    <p class="center-align">
      If you decide to save the harmony, the following prompt will be displayed. Enter a descriptive name for the harmony and hit <i>Save</i>.
    </p>

<div class = "row center">
    <img class="z-depth-2 responsive-img" src="/static/img/howto5.png">
</div>

  </div>
</div>

<div class="parallax-container" style="height:400px">
    <div class="parallax"><img src="/static/img/sax.jpg"></div>
  </div>



<!-- Editing Tracks --> 
<div class="section howToSection z-depth-5">
  <div class="container">   
    <h4 class="center-align howtoHeader"> Editing Tracks </h4>
    <p class="center-align">
      Note: you must be logged in to edit tracks <br>
     Navigate to a track page. All layers can be muted, whether or not you are logged in. To <i> Delete Layer </i>, if you are the owner of the track, you can delete any layer associated with the track. If you are not the creator of the track, you can only delete your own layers. In the following example, since the track creator is "Noah Zweben", and I am logged in as itchynose27, I am only able to delete the <i>low chorus harmony</i> layer because I recorded it. This feature ensures that the original creator of a track has the final say on the harmonies included in the track.<br>
     <i> Please note that deleting layers and tracks cannot be undone</i>
    </p>

    <div class = "row center">
    <img class="z-depth-2 responsive-img" src="/static/img/howto6.png">
  </div>
    <p class="center-align">
      If you are the creator of a track, you may also delete the entire track.
    </p>

    <div class = "row center">
    <img class="z-depth-2 responsive-img" src="/static/img/howto7.png">
    </div>
  </div>
</div>
{% endblock %}

app/templates/index.html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>MusicWebs</title>

    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400' rel='stylesheet' type='text/css'>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    <script src="/static/js/init.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css">

    <link rel="stylesheet" type="text/css" href="/static/css/styles.css" media="screen,projection"/>
  </head>
  <body>


    {% for message in get_flashed_messages() %}
      <p><b>Error</b>: {{ message }}</p>
    {% endfor %}
    <div class="parallax-container">


      
      <div class="navbar-fixed">
        <nav class="transparent">
          <div class="nav-wrapper">
            <div class="nav-container">
              <div><a href="{{url_for('home.home_page')}}" class="brand-logo">MusicWebs</a></div>

              <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><div class="new-track-btn-container">
                  <a href="{{ url_for('track.new_track') }}" class="login-btn right waves-effect waves-light btn">New Track</a>
                </div></li>
                <li><a href="{{ url_for('track.all_tracks')}}">Discover Tracks</a></li>

                <li><a href="{{ url_for('user.findUser',username = current_user.username)}}"><ul>
                {% if current_user.is_authenticated %}
                    <!-- <li><i class="material-icons">perm_identity</i></li> -->
                Hi, {{current_user.username }}!
                </ul></a></li>

            <li><a href="{{ url_for('login.logout') }}">Logout </a></li>
                    {% endif %}



                {% if not current_user.is_authenticated %}
                <li><div class="login-btn-container">
                  <a href="{{ url_for('login.oauth_authorize', provider='facebook') }}" class="login-btn right waves-effect waves-light btn">Login</a>
                </div></li>
                {% endif %}
              
              </ul>
            </div>
          </div>
        </nav>
      </div>


      <div class="valign">
        <div class="section no-pad-bot">
          <div class="big_header_container">
            <div class="row center">
              <h5 class="header col s12 big_header left-align">Collaborate on open-source tracks with musicians around the world</h5>
            </div>
          </div>
          <div class="small_header_container">
            <div class="row center">
              <h3 class="header col s12 small_header left-align">MusicWebs is a way to create tracks, add harmonies to other users' songs, and share your results with the world.</h3>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row center">
            {%if not current_user.is_authenticated%}
            <a href="{{ url_for('login.oauth_authorize', provider='facebook') }}" class="signup-btn center waves-effect waves-light btn-large">Get Started with Facebook</a>
            {% endif %}
          </div>
          <div class = "row center">
            <a href="{{ url_for('home.howto_page') }}" class="center waves-effect waves-light btn">learn how to use</a>
          </div>
        </div>
      </div>
      <div class="parallax"><img src="/static/img/background.png"></div>
    </div>

   
  </body>
</html>

app/templates/login.html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>MusicWebs</title>

    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400' rel='stylesheet' type='text/css'>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    <script src="/static/js/init.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css">

    <link rel="stylesheet" type="text/css" href="/static/css/styles.css" media="screen,projection"/>
  </head>
  <body>
    {% for message in get_flashed_messages() %}
      <p><b>Error</b>: {{ message }}</p>
    {% endfor %}
    <div class="parallax-container">

      <div class="navbar-fixed">
        <nav class="transparent">
          <div class="nav-wrapper">
            <div class="nav-container">
              <div><a href="{{url_for('home.home_page')}}" class="brand-logo">MusicWebs</a></div>

                <div class="login-btn-container">
                  <a href="{{ url_for('login.oauth_authorize', provider='facebook') }}" class="login-btn right waves-effect waves-light btn">Login</a>
                </div>
            </div>
            
          </div>
        </nav>
      </div>
      <div class="valign">
        <div class="section no-pad-bot">
          <div class="big_header_container">
            <div class="row center">
              <h5 class="header col s12 big_header left-align">Collaborate with musicians around the world</h5>
            </div>
          </div>
          <div class="small_header_container">
            <div class="row center">
              <h3 class="header col s12 small_header left-align">MusicWebs is a way to upload your tracks, add tracks to other songs, and share your results with the world.</h3>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row center">
            <a href="{{ url_for('login.oauth_authorize', provider='facebook') }}" class="signup-btn center waves-effect waves-light btn-large">Get Started with Facebook</a>
          </div>
        </div>
      </div>
      <div class="parallax"><img src="/static/img/background.png"></div>
    </div>
  </body>
</html>

app/templates/navbar.html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>MusicWebs</title>

    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400' rel='stylesheet' type='text/css'>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    <script src="/static/js/init.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css">

    <link rel="stylesheet" type="text/css" href="/static/css/styles.css" media="screen,projection"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body >

{% for message in get_flashed_messages() %}
      <p><b>Error</b>: {{ message }}</p>
    {% endfor %}
      <div class="navbar-fixed">
        <nav class="blue-grey darken-2">
          <div class="nav-wrapper">
            <div class="nav-container">
              <div><a href="{{url_for('home.home_page')}}" class="brand-logo">MusicWebs</a></div>

              <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><div class="new-track-btn-container">
                  <a href="{{ url_for('track.new_track') }}" class="login-btn right waves-effect waves-light btn">New Track</a>
                </div></li>
                <li><a href="{{ url_for('track.all_tracks')}}">Discover Tracks</a></li>

                <li><a href="{{ url_for('user.findUser',username = current_user.username)}}"><ul>
                {% if current_user.is_authenticated %}
                    <li><i class="material-icons">perm_identity</i></li>
                Hi, {{current_user.username }}!
                </ul></a></li>

            <li><a href="{{ url_for('login.logout') }}">Logout </a></li>
                    {% endif %}



                {% if not current_user.is_authenticated %}
                <li><div class="login-btn-container">
                  <a href="{{ url_for('login.oauth_authorize', provider='facebook') }}" class="login-btn right waves-effect waves-light btn">Login</a>
                </div></li>
                {% endif %}
              
              </ul>
            </div>
          </div>
        </nav>
      </div>

{% block content %}{% endblock %}
  </body>
</html>

app/templates/newTrack.html
{% extends "navbar.html" %} 
{% block content %} 

<div class = "container row">


 <div class="input-field">
 <h5>Name of Track</h5>
<input class = "validate" type="text" id = "nameForm" placeholder =" e.g Single Ladies"/>
</div>

 <div class="input-field">
<h5>Original Artist</h5>
<input class = "validate"  type="text" id = "artistForm" placeholder =" e.g Beyonce or Original"/>
</div>

<div class = "input-field">
<h5> Keep Hidden </h5> 
hidden tracks will only be accessible by the creator and people with the link, use this feature for private collaborations
<br><input type="checkbox" id = "hiddenBox"/><label for="hiddenBox">Hidden</label>
</div>

<br>
<div class="row center">
<button class = "waves-effect deep-orange lighten-2 waves-light btn" id = "recordButton" onclick="toggleRecord()">Add Recording for New Track</button>
</div>

<div class="row center">
<button class = "btn modal-trigger waves-effect deep-orange lighten-2 waves-light " data-target="modal1" id = "uploadButton" onclick="">Upload Audio to Start Track</button>
</div>

<!-- MODAL --> 
  <div id="modal1" class="modal">
    <div class="modal-content">

       <div class="input-field">
      <h3 class="center-align">Select File to Upload</h3>
      <input class = "validate"  type="file" id = "fileForm" accept=".wav,.m4a,.mp3/>">
    </div>

    </div>
    <div class="modal-footer">
      <button class="waves-effect waves-light btn deep-orange lighten-1" onclick = "newUpload()">Save</button>
    </div>
  </div>


<div id = "layerInfo"> 
	<div id = "layerContainer"></div>
	 <div id="wave" class="hide"></div>
</div>

<div class="row center">
<button id="playButton" class= "hide waves-effect waves-light btn" onclick ="togglePlay()">Play</button>
</div>

</div> 

<script src="{{ url_for('static', filename='js/wavesurferMyEdits.js') }}"></script>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>

 <script src="{{ url_for('static', filename='js/recorder.js') }}"></script>
<script src="{{ url_for('static', filename='js/newTrack.js') }}"></script>
<script src="{{ url_for('static', filename='js/recordCountdown.js') }}"></script>


{% endblock %}

app/templates/track.html
{% extends "navbar.html" %} 
{% block content %} 


<div class = "row">
  <div class = "col s11 offset-s1">
     <h2>{{track.trackName}}</h2>
     <h5> opb: {{track.originalArtist}}</h5>
        <div class="js-data"
            data-id="{{ track.id }}">
        </div>
     <h5>Track owner: <a href="{{url_for('user.findUser',username=track.createdBy)}}">{{track.createdBy}}</a></h5>
    
    {% if current_user.username == track.createdBy %}
      <a href="{{ url_for('track.del_track', trackID = track.id)  }}">Delete Track</a>
    
    {%endif%}
     
    {% if not current_user.is_authenticated %}
    <p> You must <a href="{{ url_for('login.index') }}">log in </a> in order to record layers to this track </p>
    {% endif %}
  </div>
</div>



<div class="row">

      <div id = "layerInfo" class="col s11 offset-s1"> 
          <div id = "layerContainer">
                  {% for layer in track.layers %}
               
                              
                                  <div class = "grey darken-1">{{ layer.layerName}}<br> By: <a href="{{url_for('user.findUser',username=layer.createdBy)}}"> 
                                      {{ layer.createdBy }} </a> 
                                      <br>
                                      {% if current_user.username == layer.createdBy or current_user.username == track.createdBy %}
                                          <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Permanently delete layer" href="{{ url_for('track.del_layer', trackID = track.id, layerID = layer.layerID)}}"> 
                                          <button class="waves-effect waves-light btn-floating editButton">Del</button></a>
                                      {% endif %}
                                  </div>

                              <li style = "display: none"> {{ layer.layerID }} </li>
                              <li style = "display: none" class="path"> {{layer.layerPath}}  </li>
                              <li  style = "display: none" class="startTime">{{layer.startTime}} </li>

                              
                  {% endfor %}
           </div>
           <div id="wave"></div>
      </div>
</div>


<div id="playPanel">
    <button id="playButton" class= "waves-effect waves-light btn" onclick ="togglePlay()">Play</button>
    {% if current_user.is_authenticated %}
    <button id="recordButton" class= "waves-effect waves-light btn" onclick="toggleRecord()">Start Recording</button>
    {% endif %}
</div>


<!-- MODAL --> 
  <div id="modal1" class="modal">
    <div class="modal-content">

       <div class="input-field">
      <h3 class="center-align">Enter layer name to save</h3>
      <input class = "validate"  type="text" id = "layerName" placeholder ="e.g. Tenor Harmony"/>
      </div>

    </div>
    <div class="modal-footer">
      <button class="waves-effect waves-light btn deep-orange lighten-1" onclick = "postLayer()">Save</button>
    </div>
  </div>



<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
 --><!-- <script src="{{ url_for('static', filename='js/jquery-1.11.3.min.js') }}"></script> 
 --><script src="{{ url_for('static', filename='js/wavesurferMyEdits.js') }}"></script>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
 <script src="{{ url_for('static', filename='js/recorder.js') }}"></script>
<script src="{{ url_for('static', filename='js/liveRecord.js') }}"></script>
<script src="{{ url_for('static', filename='js/recordCountdown.js') }}"></script>

{% endblock %}